source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :generate_multiple_pod_projects => true, :warn_for_unused_master_specs_repo => false
platform :ios, '12.0'

use_frameworks!

target 'Example' do
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  
  pod 'NetworkKit/Core',  :path => '../'
  pod 'NetworkKit/CoreMocks', :path => '../'
  
  pod 'NetworkKit/NetworkQueue',  :path => '../'
  pod 'NetworkKit/NetworkQueueMocks',  :path => '../'
end

target 'ExampleTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
