#!/bin/bash

# https://github.com/nicklockwood/SwiftFormat
# https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md

# To exclude some directories, update the file '.rules' (--exclude param)

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source Tools/src-utils/colors
source Tools/src-utils/check-versions

SWIFT_VERSION=5.7.1
RULES="Tools/.rules"

echo -e "\n*** Doing code formatting transformations. ***"

echo -e "\n${COLOR_GREEN}Formatting source files INSIDE 'NetworkCompose'${COLOR_RESET}\n"

#ZigKits
swiftformat --swiftversion $SWIFT_VERSION --config $RULES \
    --exclude NetworkCompose/implementation/src/Network/CircuitBreaker/CircuitBreaker.swift \
    --exclude NetworkCompose/interfaces/src/NetworkSession.swift \
    --exclude NetworkCompose/interfaces/src/NetworkSessionExecutorInteface.swift \
    "NetworkCompose/"

echo -e "\n*** Finished formatting transformations. ***"
